// import { Toaster } from "@/components/ui/toaster"
import AuthProvider from "@/context/AuthProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          {children}
          {/* <Toaster /> */}
        </body>
      </html>
    </AuthProvider>
  )
}
